name: Release - Build et Package
run-name: Release - Build et Package

on:
  push:
    tags:
      - "v*"
      - "release-*"

env:
  PROJECT_NAME: bluemap-banner-point
  JAVA_VERSION: 21

jobs:
  # Job de notification de début de release
  notify-release-start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Extraction de la version
        id: version
        run: |
          echo "🔍 Extraction de la version..."
          echo "GITEA_REF: $GITEA_REF"
          echo "GITEA_REF_NAME: $GITEA_REF_NAME"
          echo "GITEA_REF_NAME (github): ${{ gitea.ref_name }}"

          # Méthode 1: Utiliser gitea.ref_name (équivalent à github.ref_name)
          VERSION="${{ gitea.ref_name }}"
          VERSION=${VERSION#v}
          VERSION=${VERSION#release-}

          # Si la version est vide, essayer avec GITEA_REF_NAME
          if [ -z "$VERSION" ]; then
            echo "⚠️ Version vide depuis gitea.ref_name, essai avec GITEA_REF_NAME..."
            VERSION=${GITEA_REF_NAME#v}
            VERSION=${VERSION#release-}
          fi

          # Si toujours vide, essayer avec GITEA_REF
          if [ -z "$VERSION" ]; then
            echo "⚠️ Version vide depuis GITEA_REF_NAME, essai avec GITEA_REF..."
            VERSION=${GITEA_REF#refs/tags/}
            VERSION=${VERSION#v}
            VERSION=${VERSION#release-}
          fi

          # Si toujours vide, extraire depuis pom.xml
          if [ -z "$VERSION" ]; then
            echo "⚠️ Version toujours vide, extraction depuis pom.xml..."
            VERSION=$(grep -o '<version>[^<]*</version>' pom.xml | head -1 | sed 's/<version>\(.*\)<\/version>/\1/')
          fi

          echo "📋 Version extraite: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION"

      - name: Notification de début de release
        run: |
          if [ -n "${{ secrets.DISCORD_WEBHOOK_URL }}" ]; then
            curl -X POST "${{ secrets.DISCORD_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{
              "embeds": [{
                "title": "🚀 Début de la release",
                "description": "**Projet:** ${{ env.PROJECT_NAME }}\n**Version:** ${{ steps.version.outputs.version }}\n**Tag:** ${{ gitea.ref_name }}\n**Auteur:** ${{ gitea.actor }}",
                "color": 15844367,
                "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%S.000Z)'"
              }]
            }'
          fi

  # Job principal de build et packaging
  build-release:
    runs-on: ubuntu-latest
    needs: notify-release-start
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Extraction de la version
        id: version
        run: |
          echo "🔍 Extraction de la version..."
          echo "GITEA_REF: $GITEA_REF"
          echo "GITEA_REF_NAME: $GITEA_REF_NAME"
          echo "GITEA_REF_NAME (github): ${{ gitea.ref_name }}"

          # Méthode 1: Utiliser gitea.ref_name (équivalent à github.ref_name)
          VERSION="${{ gitea.ref_name }}"
          VERSION=${VERSION#v}
          VERSION=${VERSION#release-}

          # Si la version est vide, essayer avec GITEA_REF_NAME
          if [ -z "$VERSION" ]; then
            echo "⚠️ Version vide depuis gitea.ref_name, essai avec GITEA_REF_NAME..."
            VERSION=${GITEA_REF_NAME#v}
            VERSION=${VERSION#release-}
          fi

          # Si toujours vide, essayer avec GITEA_REF
          if [ -z "$VERSION" ]; then
            echo "⚠️ Version vide depuis GITEA_REF_NAME, essai avec GITEA_REF..."
            VERSION=${GITEA_REF#refs/tags/}
            VERSION=${VERSION#v}
            VERSION=${VERSION#release-}
          fi

          # Si toujours vide, extraire depuis pom.xml
          if [ -z "$VERSION" ]; then
            echo "⚠️ Version toujours vide, extraction depuis pom.xml..."
            VERSION=$(grep -o '<version>[^<]*</version>' pom.xml | head -1 | sed 's/<version>\(.*\)<\/version>/\1/')
          fi

          echo "📋 Version extraite: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION"

      - name: Installation de Java ${{ env.JAVA_VERSION }}
        run: |
          echo "🔧 Installation de Java ${{ env.JAVA_VERSION }}..."
          sudo apt-get update
          sudo apt-get install -y openjdk-${{ env.JAVA_VERSION }}-jdk
          java -version
          echo "✅ Java installé"

      - name: Installation de Maven
        run: |
          echo "📦 Installation de Maven..."
          sudo apt-get install -y maven
          mvn -version
          echo "✅ Maven installé"

      - name: Vérification des traductions
        run: |
          echo "🔍 Vérification des clés de traduction..."
          python3 check_translations.py
          if [ $? -ne 0 ]; then
            echo "❌ Erreur dans les traductions"
            exit 1
          fi
          echo "✅ Traductions OK"

      - name: Build du package final
        run: |
          echo "📦 Build du package final..."
          mvn clean package -DskipTests
          if [ $? -ne 0 ]; then
            echo "❌ Erreur de build"
            exit 1
          fi
          echo "✅ Build réussi"

      - name: Création du lien latest
        run: |
          echo "🏷️ Création du lien latest..."
          echo "📋 Version extraite: ${{ steps.version.outputs.version }}"
          echo "📋 Nom du projet: ${{ env.PROJECT_NAME }}"

          cd target
          echo "📁 Contenu du dossier target:"
          ls -la *.jar

          # Trouver le JAR principal (celui généré par Maven avec la version du pom.xml)
          # Exclure les fichiers "original-*" et "*-shaded"
          MAIN_JAR=$(ls -t *.jar | grep --invert-match "original-" | grep --invert-match "-shaded" | head -1)

          if [ -z "$MAIN_JAR" ]; then
            echo "❌ Aucun JAR principal trouvé"
            exit 1
          fi

          echo "✅ JAR principal trouvé: $MAIN_JAR"

          # Créer une copie pour latest
          cp "$MAIN_JAR" "${{ env.PROJECT_NAME }}-latest.jar"
          echo "✅ Lien latest créé: ${{ env.PROJECT_NAME }}-latest.jar"

            - name: Vérification du contenu du JAR
        run: |
          echo "🔍 Vérification du contenu du JAR..."
          cd target
          # Chercher le JAR principal
          JAR_FILE=$(ls -t *.jar | grep --invert-match "original-" | grep --invert-match "-shaded" | head -1)

          echo "🔍 Vérification du JAR: $JAR_FILE"
          jar -tf "$JAR_FILE" | head -20
          echo "✅ Contenu du JAR vérifié"

            - name: Création du checksum
        run: |
          echo "🔐 Création du checksum..."
          cd target
          # Chercher le JAR principal
          JAR_FILE=$(ls -t *.jar | grep --invert-match "original-" | grep --invert-match "-shaded" | head -1)

          echo "🔐 Création du checksum pour: $JAR_FILE"
          sha256sum "$JAR_FILE" > "$JAR_FILE.sha256"
          echo "✅ Checksum créé: $JAR_FILE.sha256"

      - name: Upload des artefacts de release
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: |
            target/*.jar
            target/*.sha256
          retention-days: 90

  # Job de notification de fin de release
  notify-release-end:
    runs-on: ubuntu-latest
    needs: build-release
    if: always()
    steps:
      - name: Extraction de la version
        id: version
        run: |
          VERSION=${GITEA_REF#refs/tags/}
          VERSION=${VERSION#v}
          VERSION=${VERSION#release-}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Notification de fin de release
        run: |
          if [ -n "${{ secrets.DISCORD_WEBHOOK_URL }}" ]; then
            if [ "${{ needs.build-release.result }}" == "success" ]; then
              STATUS="✅ Release réussie"
              COLOR="3066993"
              EMOJI="🎉"
              DESCRIPTION="**Projet:** ${{ env.PROJECT_NAME }}\n**Version:** ${{ steps.version.outputs.version }}\n**Tag:** ${{ gitea.ref_name }}\n**Auteur:** ${{ gitea.actor }}\n\n📦 Package JAR créé avec succès"
            else
              STATUS="❌ Release échouée"
              COLOR="15158332"
              EMOJI="💥"
              DESCRIPTION="**Projet:** ${{ env.PROJECT_NAME }}\n**Version:** ${{ steps.version.outputs.version }}\n**Tag:** ${{ gitea.ref_name }}\n**Auteur:** ${{ gitea.actor }}\n\n❌ Erreur lors de la création du package"
            fi

            curl -X POST "${{ secrets.DISCORD_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{
              "embeds": [{
                "title": "'"$EMOJI $STATUS"'",
                "description": "'"$DESCRIPTION"'",
                "color": '"$COLOR"',
                "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%S.000Z)'"
              }]
            }'
          fi
