name: Release - Build et Package
run-name: Release - Build et Package

on:
  push:
    tags:
      - "v*"
      - "release-*"

env:
  PROJECT_NAME: bluemap-banner-point
  JAVA_VERSION: 21
  MAVEN_OPTS: -Dmaven.repo.local=${{ github.workspace }}/.m2/repository

jobs:
  # Job de validation préliminaire
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Extraction de la version
        id: version
        run: |
          echo "🔍 Extraction de la version..."
          VERSION="${{ gitea.ref_name }}"
          VERSION=${VERSION#v}
          VERSION=${VERSION#release-}
          echo "📋 Version extraite: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Validation du pom.xml
        run: |
          echo "🔍 Validation du pom.xml..."
          if [ ! -f "pom.xml" ]; then
            echo "❌ pom.xml manquant"
            exit 1
          fi
          echo "✅ pom.xml trouvé"

      - name: Validation des fichiers de traduction
        run: |
          echo "🔍 Validation des fichiers de traduction..."
          if [ ! -f "check_translations.py" ]; then
            echo "❌ Script de vérification des traductions manquant"
            exit 1
          fi
          if [ ! -d "src/main/resources/lang" ]; then
            echo "❌ Répertoire de traductions manquant"
            exit 1
          fi
          echo "✅ Fichiers de traduction trouvés"

      - name: Notification de début de release
        run: |
          if [ -n "${{ secrets.DISCORD_WEBHOOK_URL }}" ]; then
            curl -X POST "${{ secrets.DISCORD_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{
              "embeds": [{
                "title": "🚀 Début de la release",
                "description": "**Projet:** ${{ env.PROJECT_NAME }}\n**Version:** ${{ steps.version.outputs.version }}\n**Tag:** ${{ gitea.ref_name }}\n**Auteur:** ${{ gitea.actor }}\n\n🔍 Validation en cours...",
                "color": 15844367,
                "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%S.000Z)'"
              }]
            }'
          fi

  # Job de build
  build:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Extraction de la version
        id: version
        run: |
          VERSION="${{ gitea.ref_name }}"
          VERSION=${VERSION#v}
          VERSION=${VERSION#release-}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Setup Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"
          cache: "maven"

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Vérification des traductions
        run: |
          echo "🔍 Vérification des clés de traduction..."
          python3 check_translations.py
          if [ $? -ne 0 ]; then
            echo "❌ Erreur dans les traductions"
            exit 1
          fi
          echo "✅ Traductions OK"

      - name: Compilation
        run: |
          echo "🔨 Compilation..."
          mvn clean compile
          if [ $? -ne 0 ]; then
            echo "❌ Erreur de compilation"
            exit 1
          fi
          echo "✅ Compilation réussie"

      - name: Build du package final
        run: |
          echo "📦 Build du package final..."
          mvn package -DskipTests
          if [ $? -ne 0 ]; then
            echo "❌ Erreur de build"
            exit 1
          fi
          echo "✅ Build réussi"

      - name: Validation du JAR
        run: |
          echo "🔍 Validation du JAR..."
          cd target

          # Vérifier que le JAR existe
          JAR_FILE=$(ls bluemap-banner-point-*.jar 2>/dev/null | head -1)
          if [ -z "$JAR_FILE" ]; then
            echo "❌ Aucun JAR trouvé"
            exit 1
          fi

          # Vérifier que le JAR est valide
          if ! jar -tf "$JAR_FILE" > /dev/null 2>&1; then
            echo "❌ JAR corrompu"
            exit 1
          fi

          # Vérifier la présence de plugin.yml
          if ! jar -tf "$JAR_FILE" | grep -q "plugin.yml"; then
            echo "❌ plugin.yml manquant dans le JAR"
            exit 1
          fi

          echo "✅ JAR validé: $JAR_FILE"

      - name: Création du lien latest
        run: |
          echo "🏷️ Création du lien latest..."
          cd target
          JAR_FILE=$(ls bluemap-banner-point-*.jar | head -1)
          cp "$JAR_FILE" "${{ env.PROJECT_NAME }}-latest.jar"
          echo "✅ Lien latest créé"

      - name: Création des checksums
        run: |
          echo "🔐 Création des checksums..."
          cd target
          for jar in bluemap-banner-point-*.jar; do
            sha256sum "$jar" > "$jar.sha256"
            echo "✅ Checksum créé pour $jar"
          done

      - name: Upload des artefacts de release
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts-${{ steps.version.outputs.version }}
          path: |
            target/*.jar
            target/*.sha256
          retention-days: 90

  # Job de notification de fin de release
  notify-release-end:
    runs-on: ubuntu-latest
    needs: [validate, build]
    if: always()
    steps:
      - name: Extraction de la version
        id: version
        run: |
          VERSION="${{ gitea.ref_name }}"
          VERSION=${VERSION#v}
          VERSION=${VERSION#release-}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Notification de fin de release
        run: |
          if [ -n "${{ secrets.DISCORD_WEBHOOK_URL }}" ]; then
            if [ "${{ needs.build.result }}" == "success" ]; then
              STATUS="✅ Release réussie"
              COLOR="3066993"
              EMOJI="🎉"
              DESCRIPTION="**Projet:** ${{ env.PROJECT_NAME }}\n**Version:** ${{ steps.version.outputs.version }}\n**Tag:** ${{ gitea.ref_name }}\n**Auteur:** ${{ gitea.actor }}\n\n📦 Package JAR créé avec succès\n🔐 Checksums générés"
            else
              STATUS="❌ Release échouée"
              COLOR="15158332"
              EMOJI="💥"
              DESCRIPTION="**Projet:** ${{ env.PROJECT_NAME }}\n**Version:** ${{ steps.version.outputs.version }}\n**Tag:** ${{ gitea.ref_name }}\n**Auteur:** ${{ gitea.actor }}\n\n❌ Erreur lors de la création du package\n\n**Détails:**\n- Validation: ${{ needs.validate.result }}\n- Build: ${{ needs.build.result }}"
            fi

            curl -X POST "${{ secrets.DISCORD_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{
              "embeds": [{
                "title": "'"$EMOJI $STATUS"'",
                "description": "'"$DESCRIPTION"'",
                "color": '"$COLOR"',
                "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%S.000Z)'"
              }]
            }'
          fi
